language: rust
sudo: false

matrix:
  include:
    - rust: 1.27.0
    - rust: stable
    - rust: beta
    - rust: nightly
      env:
        FEATURES='test_compiletest'
env:
  global:
    - HOST=x86_64-unknown-linux-gnu

branches:
  only:
    - master

# the main build
script:
  - |
      cargo build -v --no-default-features &&
      cargo test -v --no-default-features &&
      cargo build -v --features=$FEATURES &&
      cargo test -v --features=$FEATURES &&
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        cargo bench -v --no-run
      else
        true
      fi &&
      cargo doc -v

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
