language: rust
sudo: false

# run builds for all the trains (and more)
rust:
  - 1.27.0
  - stable
  - beta
  - nightly
    env:
        - FEATURES='test_compiletest'
branches:
  only:
    - master

# the main build
script:
  - |
      cargo build -v --no-default-features &&
      cargo test -v --no-default-features &&
      cargo build -v --features=$FEATURES &&
      cargo test -v --features=$FEATURES &&
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        cargo bench -v --no-run
      else
        true
      fi &&
      cargo doc -v

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
