language: rust
sudo: false

# run builds for all the trains (and more)
rust:
  - stable
  - nightly
branches:
  only:
    - master

# the main build
script:
  - |
      cargo build &&
      cargo --only nightly test &&
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        cargo test
      else
        true
      fi &&
      cargo bench &&
      cargo doc

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
