[package]
name = "indexing"
version = "0.1.0"
authors = ["bluss", "Gankro"]

[lib]

path = "indexing.rs"

[dev-dependencies]
compiletest_rs = "0.0.10"
rand = "0.3"
quickcheck = "0.2"

[profile.bench]
debug = true
