[package]
name = "indexing"
version = "0.1.0"
authors = ["bluss"]

license = "MIT/Apache-2.0"
repository = "https://github.com/bluss/indexing"
documentation = "http://bluss.github.io/indexing"

description = "Sound unchecked indexing using “generativity”; a type system approach to indices and ranges that are trusted to be in bounds."

keywords = ["data-structure", "generativity"]

[lib]
path = "indexing.rs"

[dev-dependencies]
compiletest_rs = "0.0.10"
rand = "0.3"
quickcheck = "0.2"

[profile.bench]
debug = true
